apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  ports:
  - port: {{ .Values.service.ports.server }}
    targetPort: {{ .Values.service.ports.server }}
    protocol: TCP
    name: grpc
  - port: {{ .Values.service.ports.external }}
    targetPort: {{ .Values.service.ports.internal }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.info.port }}
    targetPort: {{ .Values.service.info.port }}
    protocol: TCP
    name: info
  selector:
    app: {{ template "fullname" . }}
  type: "{{ .Values.service.type }}"
  {{ if eq "LoadBalancer" .Values.service.type }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  {{ if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $IPrange := .Values.service.loadBalancerSourceRanges }}
  - {{ $IPrange }}
  {{- end }}
  {{- end }}
  {{- end }}
