main:
  ## Count of instances
  ##
  replicaCount: 3

  ## Count of revisions saved in release history
  ##
  revisionHistoryLimit: 5

  ## Value which provide max unavailable state ( percents )
  ##
  maxUnavailable: 25%

  ## Ingress
  ## Optional: Contour - Ingress controller with Envoy
  ## to proxy all services using shared IP address.
  ##
  ingress:
    ## If true, Ingress will be created
    ##
    enabled: true

    ## Use Contour ingress routes
    ##
    contour:
      enabled: false

    ## TLS configs
    ##
    tls:
      ##
      enabled: true
      ##
      secretName: {{[ .Name ]}}.prod.net-certs

    ## Ingress route hosts
    ##
    hosts:
      ## gRPC service host
      - name: grpc
        host: {{[ .Name ]}}-grpc.prod.net
        path: /
        port: {{[ .API.Config.Port ]}}

      ## REST service host
      - name: rest
        host: {{[ .Name ]}}-rest.prod.net
        path: /
        port: {{[ .API.Config.Gateway.Port ]}}
        {{[- if .API.CORS.Enabled ]}}
        ## CORS configs
        ##
        cors:
          ##
          enabled: true
          allow:
            credentials: true
            origin:
              - {{[ .Name ]}}-rest.prod.net
            methods:
              - GET
              - POST
              - OPTIONS
            headers:
              - authorization
              - cache-control
          expose:
            headers:
              - Content-Length
              - Content-Range
          maxAge: "10m"
        {{[- end ]}}

  service:
    ## Logger format and level
    ##
    logger:
      ## logging format (available formats: json, txt)
      format: json
      ## logging level (0 - debug, 1 - info, 2 - warning, etc)
      level: 2

      ## logging time
      time: false

  ## Resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 30m
      memory: 64Mi
    requests:
      cpu: 30m
      memory: 32Mi
